### ISSUE TITLE
building issue

### ISSUE THREAD

**Issue by RaimundK2** [JuliaPackageMirrors/CPLEX.jl#1]
While CPLEX worked fine until yesterday, today for some reason CPLEX had to be rebuilt. However this was not possible, it requires 22.1, 20.1 or 12.1 of Cplex. I had installes 22.1.1 all the time.
It is somehow annoying when a minor version change leads to a major issue ...

**Comment by StefanKarpinski** [comment]
This is not the CPLEX package repo, it's a (very old) fork.

**Comment by RaimundK2** [comment]
Sorry
________________________________
Von: Stefan Karpinski ***@***.***>
Gesendet: Montag, 20. März 2023 16:15
An: JuliaPackageMirrors/CPLEX.jl ***@***.***>
Cc: Raimund Kovacevic ***@***.***>; Author ***@***.***>
Betreff: Re: [JuliaPackageMirrors/CPLEX.jl] building issue (Issue #1)


This is not the CPLEX package repo, it's a (very old) fork.
